### PR TITLE
Prevent Lockdown from detecting alt-tabbing

### LINKED ISSUE #11: Lockdown detects alt tabbing
Hi there,

As of this week’s update, if you have the windows sandbox minimized and opening it up again, it detects that and sends to the instructor about it.

Even if you for example open Google chrome over the windows sandbox, then minimize Google chrome, a warning would pop up. If you do it again, the lockdown closes down.

The same thing does for using on a touch screen as well.

### PR DESCRIPTION
**Pull request by mayed505**
Prevent Lockdown from detecting windows changes... temporarily...

Fixes #11

### CODE REVIEW

**Comment by mayed505** [comment]
I've tested this patch for around 10 minutes mostly, I will update this pull request if the changes failed to prevent detections.

**Comment by gucci-on-fleek** [comment]
That's all that it needed? Well that's sure convenient. Merged, and thanks!

**Comment by mayed505** [comment]
Yep, worked like a charm!

**Comment by mayed505** [comment]
Although. Next on the list… prevent lockdown from auto updating (probably version spoofing if possible).

**Comment by gucci-on-fleek** [comment]
That would be tricky. I'm assuming that there are 3 components to the version check.

1. The _Browser_ asks the Respondus server for the most recent version. If the _Browser_ thinks that it's out-of-date, it refuses to launch and requests the user to update. 

    This is fairly simple to patch. We'd just need to proxy the network and rewrite any responses from the server that contain the "current version". We could also binary patch the _Browser_, but that wouldn't be fun.

2. The _Browser_ broadcasts its version to the School server whenever you open an exam. The server refuses to send the exam if the version is out-of-date.

    Same as before, we would just rewrite the version string in a proxy.

3. Some updates to the _Browser_ will make genuinely incompatible changes. Since this is an unexpected state for the _Browser_, the School server, and the Respondus server, pretty much anything could happen here. The _Browser_ may randomly crash halfway through, the exam may appear to go well but none of the answers are submitted, the server detects this and alerts the school, etc.

    Unless someone is analyzing each new update as they are released to make sure that there are no incompatible changes, there's not really anything that we can do to prevent this.

**Comment by mayed505** [comment]
Well, you’re definitely right. I guess we will stick to patching over their detections over time. :)

**Comment by RareSnack** [comment]
> That's all that it needed? Well that's sure convenient. Merged, and thanks!

Just to clarify, alt-tabbing works fine but minimizing the window does not.

https://github.com/gucci-on-fleek/lockdown-browser/assets/48540592/449f0171-7688-4ff4-9b11-effc7b11519c

**Pull request merged**
